services:
  chronos:
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
    depends_on:
      otel-collector:
        condition: service_started

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: Jaeger
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - chronos

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otelcol
    restart: unless-stopped
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ../otel/otelcol-config.yml:/etc/otelcol-config.yml:ro
    ports:
      - "1888:1888"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger-all-in-one
    networks:
      - chronos
