use std::collections::HashMap;
use std::env;

use opentelemetry::global;
use opentelemetry::metrics::{Counter as OtlpCounter, Histogram as OtlpHistogram, Unit};
use opentelemetry::KeyValue;
use opentelemetry_otlp::WithExportConfig;
use prometheus::{histogram_opts, opts, CounterVec as PromCounterVec, HistogramVec as PromHistogramVec, Registry};

use crate::metrics::generated::{MetricDefinition, MetricId, MetricKind, METRIC_DEFINITIONS};

const OTEL_METRICS_EXPORTER: &str = "OTEL_METRICS_EXPORTER";
const OTEL_EXPORTER_OTLP_ENDPOINT: &str = "OTEL_EXPORTER_OTLP_ENDPOINT";
const OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: &str = "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT";
const OTEL_EXPORTER_OTLP_PROTOCOL: &str = "OTEL_EXPORTER_OTLP_PROTOCOL";
const OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: &str = "OTEL_EXPORTER_OTLP_METRICS_PROTOCOL";
const PROMETHEUS_NAMESPACE: &str = "chronos";

type MetricLabels<'a> = &'a [(&'static str, String)];

trait MetricsBackend: Send + Sync {
    fn inc_counter(&self, id: MetricId, value: u64, labels: MetricLabels<'_>);
    fn observe_histogram(&self, id: MetricId, value: f64, labels: MetricLabels<'_>);
    fn render_prometheus(&self) -> Option<String>;
    fn shutdown(&self);
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MetricsExporter {
    Prometheus,
    Otlp,
}

impl MetricsExporter {
    pub fn from_env() -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        match env::var(OTEL_METRICS_EXPORTER).unwrap_or_else(|_| "prometheus".to_string()).as_str() {
            "prometheus" => Ok(Self::Prometheus),
            "otlp" => {
                require_grpc_protocol()?;
                Ok(Self::Otlp)
            }
            "none" => Err("metrics exporter disabled by OTEL_METRICS_EXPORTER=none".into()),
            other => Err(format!("unsupported {OTEL_METRICS_EXPORTER} value: {other}").into()),
        }
    }
}

/// Runtime metrics facade for Chronos.
///
/// Metric definitions are generated by OpenTelemetry Weaver in
/// `metrics/generated/chronos_metric_definitions.rs`; this facade only chooses
/// a Prometheus or OTLP backend and records by generated metric IDs.
pub struct ChronosMetrics {
    exporter: MetricsExporter,
    backend: Box<dyn MetricsBackend>,
}

impl std::fmt::Debug for ChronosMetrics {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ChronosMetrics").field("exporter", &self.exporter).finish()
    }
}

impl ChronosMetrics {
    pub fn new() -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        Self::from_env()
    }

    pub fn from_env() -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        let exporter = MetricsExporter::from_env()?;
        let backend: Box<dyn MetricsBackend> = match exporter {
            MetricsExporter::Prometheus => Box::new(PrometheusMetricsBackend::new()?),
            MetricsExporter::Otlp => Box::new(OtlpMetricsBackend::new()?),
        };

        Ok(Self { exporter, backend })
    }

    pub fn is_prometheus(&self) -> bool {
        self.exporter == MetricsExporter::Prometheus
    }

    pub fn render_prometheus(&self) -> Option<String> {
        self.backend.render_prometheus()
    }

    pub fn shutdown(&self) {
        self.backend.shutdown();
    }

    pub fn observe_consume_latency(&self, seconds: f64, destination: &'static str, status: &'static str) {
        self.observe_histogram(MetricId::MsgConsumeLatency, seconds, consume_labels(destination, status));
    }

    pub fn observe_process_latency(&self, seconds: f64, returned: bool, status: &'static str) {
        self.observe_histogram(MetricId::MsgProcessLatency, seconds, process_labels(returned, status));
    }

    pub fn observe_wait_time(&self, seconds: f64) {
        self.observe_histogram(MetricId::MsgWaitTime, seconds, Vec::new());
    }

    pub fn observe_jitter(&self, seconds: f64) {
        self.observe_histogram(MetricId::MsgJitter, seconds, Vec::new());
    }

    pub fn messages_reset(&self, count: u64) {
        self.inc_counter(MetricId::MsgReset, count, Vec::new());
    }

    fn inc_counter(&self, id: MetricId, value: u64, labels: Vec<(&'static str, String)>) {
        self.backend.inc_counter(id, value, &labels);
    }

    fn observe_histogram(&self, id: MetricId, value: f64, labels: Vec<(&'static str, String)>) {
        self.backend.observe_histogram(id, value, &labels);
    }
}

impl Drop for ChronosMetrics {
    fn drop(&mut self) {
        self.backend.shutdown();
    }
}

struct PrometheusMetricsBackend {
    registry: Registry,
    counters: HashMap<MetricId, PromCounterVec>,
    histograms: HashMap<MetricId, PromHistogramVec>,
}

impl PrometheusMetricsBackend {
    fn new() -> Result<Self, prometheus::Error> {
        let registry = Registry::new_custom(Some(PROMETHEUS_NAMESPACE.to_string()), None)?;
        let mut counters = HashMap::new();
        let mut histograms = HashMap::new();

        for definition in METRIC_DEFINITIONS {
            match definition.kind {
                MetricKind::Counter => {
                    let metric = PromCounterVec::new(opts!(definition.prometheus_name, definition.description), definition.prometheus_label_names)?;
                    registry.register(Box::new(metric.clone()))?;
                    prewarm_counter(definition, &metric)?;
                    counters.insert(definition.id, metric);
                }
                MetricKind::Histogram => {
                    let opts = match definition.buckets {
                        Some(buckets) => histogram_opts!(definition.prometheus_name, definition.description, buckets.to_vec()),
                        None => histogram_opts!(definition.prometheus_name, definition.description),
                    };
                    let metric = PromHistogramVec::new(opts, definition.prometheus_label_names)?;
                    registry.register(Box::new(metric.clone()))?;
                    prewarm_histogram(definition, &metric)?;
                    histograms.insert(definition.id, metric);
                }
            }
        }

        Ok(Self {
            registry,
            counters,
            histograms,
        })
    }
}

fn prewarm_counter(definition: &MetricDefinition, metric: &PromCounterVec) -> Result<(), prometheus::Error> {
    if definition.prometheus_label_names.is_empty() {
        metric.get_metric_with_label_values(&[])?;
        return Ok(());
    }

    for label_values in definition.prewarm_label_values {
        metric.get_metric_with_label_values(label_values)?;
    }

    Ok(())
}

fn prewarm_histogram(definition: &MetricDefinition, metric: &PromHistogramVec) -> Result<(), prometheus::Error> {
    if definition.prometheus_label_names.is_empty() {
        metric.get_metric_with_label_values(&[])?;
        return Ok(());
    }

    for label_values in definition.prewarm_label_values {
        metric.get_metric_with_label_values(label_values)?;
    }

    Ok(())
}

impl MetricsBackend for PrometheusMetricsBackend {
    fn inc_counter(&self, id: MetricId, value: u64, labels: MetricLabels<'_>) {
        if let Some(counter) = self.counters.get(&id) {
            let label_values = prometheus_label_values(id, labels);
            match counter.get_metric_with_label_values(&label_values) {
                Ok(metric) => metric.inc_by(value as f64),
                Err(err) => log::error!("metrics: failed to record counter {:?}: {}", id, err),
            }
        }
    }

    fn observe_histogram(&self, id: MetricId, value: f64, labels: MetricLabels<'_>) {
        if let Some(histogram) = self.histograms.get(&id) {
            let label_values = prometheus_label_values(id, labels);
            match histogram.get_metric_with_label_values(&label_values) {
                Ok(metric) => metric.observe(value),
                Err(err) => log::error!("metrics: failed to observe histogram {:?}: {}", id, err),
            }
        }
    }

    fn render_prometheus(&self) -> Option<String> {
        use prometheus::{Encoder, TextEncoder};

        let encoder = TextEncoder::new();
        let mut buffer = Vec::new();
        encoder.encode(&self.registry.gather(), &mut buffer).ok()?;
        String::from_utf8(buffer).ok()
    }

    fn shutdown(&self) {}
}

struct OtlpMetricsBackend {
    provider: opentelemetry_sdk::metrics::MeterProvider,
    counters: HashMap<MetricId, OtlpCounter<u64>>,
    histograms: HashMap<MetricId, OtlpHistogram<f64>>,
}

impl OtlpMetricsBackend {
    fn new() -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        let endpoint = env::var(OTEL_EXPORTER_OTLP_METRICS_ENDPOINT)
            .or_else(|_| env::var(OTEL_EXPORTER_OTLP_ENDPOINT))
            .unwrap_or_else(|_| "http://127.0.0.1:4317".to_string());
        let exporter = opentelemetry_otlp::new_exporter().tonic().with_env().with_endpoint(endpoint);
        let provider = opentelemetry_otlp::new_pipeline()
            .metrics(opentelemetry::runtime::Tokio)
            .with_exporter(exporter)
            .build()?;

        global::set_meter_provider(provider.clone());
        let meter = global::meter("chronos");

        let mut counters = HashMap::new();
        let mut histograms = HashMap::new();

        for definition in METRIC_DEFINITIONS {
            match definition.kind {
                MetricKind::Counter => {
                    let mut builder = meter.u64_counter(definition.otel_name).with_description(definition.description);
                    if let Some(unit) = definition.unit {
                        builder = builder.with_unit(Unit::new(unit));
                    }
                    counters.insert(definition.id, builder.init());
                }
                MetricKind::Histogram => {
                    let mut builder = meter.f64_histogram(definition.otel_name).with_description(definition.description);
                    if let Some(unit) = definition.unit {
                        builder = builder.with_unit(Unit::new(unit));
                    }
                    histograms.insert(definition.id, builder.init());
                }
            }
        }

        Ok(Self {
            provider,
            counters,
            histograms,
        })
    }
}

impl MetricsBackend for OtlpMetricsBackend {
    fn inc_counter(&self, id: MetricId, value: u64, labels: MetricLabels<'_>) {
        if let Some(counter) = self.counters.get(&id) {
            counter.add(value, &labels_to_key_values(labels));
        }
    }

    fn observe_histogram(&self, id: MetricId, value: f64, labels: MetricLabels<'_>) {
        if let Some(histogram) = self.histograms.get(&id) {
            histogram.record(value, &labels_to_key_values(labels));
        }
    }

    fn render_prometheus(&self) -> Option<String> {
        None
    }

    fn shutdown(&self) {
        if let Err(err) = self.provider.force_flush(&opentelemetry::Context::current()) {
            log::error!("failed to flush OTLP metrics: {}", err);
        }
        if let Err(err) = self.provider.shutdown() {
            log::error!("failed to shut down OTLP metrics provider: {}", err);
        }
    }
}

fn require_grpc_protocol() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let protocol = env::var(OTEL_EXPORTER_OTLP_METRICS_PROTOCOL)
        .or_else(|_| env::var(OTEL_EXPORTER_OTLP_PROTOCOL))
        .unwrap_or_else(|_| "grpc".to_string());

    if protocol == "grpc" {
        Ok(())
    } else {
        Err(format!("unsupported OTLP metrics protocol {protocol:?}; use grpc").into())
    }
}

fn consume_labels(destination: &'static str, status: &'static str) -> Vec<(&'static str, String)> {
    vec![("destination", destination.to_string()), ("status", status.to_string())]
}

fn process_labels(returned: bool, status: &'static str) -> Vec<(&'static str, String)> {
    vec![("returned", returned.to_string()), ("status", status.to_string())]
}

fn metric_definition(id: MetricId) -> Option<&'static MetricDefinition> {
    METRIC_DEFINITIONS.iter().find(|definition| definition.id == id)
}

fn prometheus_label_values<'a>(id: MetricId, labels: MetricLabels<'a>) -> Vec<&'a str> {
    let Some(definition) = metric_definition(id) else {
        return Vec::new();
    };

    definition
        .label_names
        .iter()
        .map(|name| {
            labels
                .iter()
                .find(|(label_name, _)| label_name == name)
                .map(|(_, value)| value.as_str())
                .unwrap_or("unknown")
        })
        .collect()
}

fn labels_to_key_values(labels: MetricLabels<'_>) -> Vec<KeyValue> {
    labels.iter().map(|(key, value)| KeyValue::new(*key, value.clone())).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::metrics::generated::METRIC_DEFINITIONS;
    use serial_test::serial;

    fn prometheus_metrics() -> ChronosMetrics {
        env::remove_var(OTEL_METRICS_EXPORTER);
        ChronosMetrics::new().unwrap()
    }

    #[test]
    #[serial]
    fn metrics_registry_creates_successfully() {
        env::remove_var(OTEL_METRICS_EXPORTER);
        assert!(ChronosMetrics::new().is_ok());
    }

    #[test]
    #[serial]
    fn generated_definitions_drive_all_runtime_metrics() {
        let metrics = prometheus_metrics();
        let output = metrics.render_prometheus().unwrap();

        for definition in METRIC_DEFINITIONS {
            assert!(
                output.contains(&format!("# HELP {PROMETHEUS_NAMESPACE}_{}", definition.prometheus_name)),
                "metric {} must be registered from generated definitions",
                definition.prometheus_name
            );
        }
    }

    #[test]
    #[serial]
    fn prometheus_metrics_use_chronos_namespace() {
        let metrics = prometheus_metrics();
        metrics.observe_jitter(0.499);
        let output = metrics.render_prometheus().unwrap();

        assert!(output.contains("# HELP chronos_msg_jitter"));
        assert!(!output.contains("# HELP msg_jitter"));
    }

    #[test]
    #[serial]
    fn msg_jitter_has_500ms_bucket() {
        let metrics = prometheus_metrics();
        metrics.observe_jitter(0.499);
        let output = metrics.render_prometheus().unwrap();

        assert!(output.contains("chronos_msg_jitter_bucket{le=\"0.5\"} 1"));
    }

    #[test]
    #[serial]
    fn msg_reset_increments_correctly() {
        let metrics = prometheus_metrics();
        metrics.messages_reset(3);
        metrics.messages_reset(2);
        let output = metrics.render_prometheus().unwrap();

        assert!(output.contains("chronos_msg_reset 5"));
    }

    #[test]
    #[serial]
    fn msg_wait_time_records_observation() {
        let metrics = prometheus_metrics();
        metrics.observe_wait_time(1.5);
        let output = metrics.render_prometheus().unwrap();

        assert!(output.contains("chronos_msg_wait_time_count 1"));
    }

    #[test]
    #[serial]
    fn labeled_metrics_record_issue_dimensions() {
        let metrics = prometheus_metrics();
        metrics.observe_consume_latency(0.05, "postgres", "pass");
        metrics.observe_process_latency(0.01, false, "fail");
        let output = metrics.render_prometheus().unwrap();

        assert!(output.contains("chronos_msg_consume_latency_count{destination=\"postgres\",status=\"pass\"} 1"));
        assert!(output.contains("chronos_msg_process_latency_count{returned=\"false\",status=\"fail\"} 1"));
    }
}
